### ISSUE TITLE
Merge `dev` branch of mkxp-z

### ISSUE THREAD

**Issue by Splendide-Imaginarius** [rainefall/mkxp-zr#1]
You may wish to merge the `dev` branch of upstream mkxp-z; it has a number of useful fixes. I'm not sure why the `release` branch is even present in the mkxp-z repo; it seems to almost never get updated (looks like maybe a relic of Ancurio's mkxp).

**Comment by Splendide-Imaginarius** [comment]
Actually maybe hold off on this, looks like there's a bug in that branch that breaks building on Linux.

**Comment by rainefall** [comment]
gonna hold off on merging until v2.4.1 gets a stable release
